###################################################
#                                                 #
#            PLUGIN MADE BY ARMOROFGLORY          #
#                                                 #
################# CONFIGURATIONFILE ###############

# Main game settings
Settings:
  minPlayersToStart: 1
  startCountdownTimer: 10
  gameDuration: 30
  allTeams: []
  Points:
    pointsPerKill: 10
    pointsPerBlock: 1
    pointsPerDeposit: 3
  
# Configure Plugin messages
Messages:
  PREFIX: "&6[&eTurfWar&6] &f"
  Errors:
    notEnoughPlayersOnline: "Messages.Errors.notEnoughPlayersOnline"

# Lobby Spawn Point
Locations:
  Lobby:

# Game Teams
Teams:
