###################################################
#                                                 #
#            PLUGIN MADE BY ARMOROFGLORY          #
#                                                 #
################# CONFIGURATIONFILE ###############

# Main game settings
Settings:
  minPlayersToStart: 2
  startCountdownTimer: 20
  gameDuration: 60
  allTeams: []
  Points:
    pointsPerKill: 10
    pointsPerBlock: 1
    pointsPerDeposit: 3
  
# Configure Plugin messages
Messages:
  PREFIX: "&6[&eTurfWar&6] &f"
  Errors:
    notEnoughPlayersOnline: "There's not enough players online to start the game!"

# Lobby Spawn Point
Locations:
  Lobby:

# Game Teams
Teams:

# mySQL Database
mySQL:
  host: 'localhost'
  port: '3306'
  database: 'minecraft'
  user: 'root'
  pass: '6154984'
